fromsklearn.model_selectionimportcross_val_score,StratifiedKFold
fromsklearn.preprocessingimportStandardScaler
fromsklearn.ensembleimportRandomForestClassifier,GradientBoostingClassifier
fromsklearn.linear_modelimportLogisticRegression
fromsklearn.metricsimportroc_curve,auc
importxgboostasxgb
importmatplotlib.pyplotasplt
importnumpyasnp
importpandasaspd
#Loadmergeddataset
ml_data=pd.read_excel("ML_dataset.xlsx")
x_numeric_columns=[
'MW', 'TPSA', 'NumHeavy', 'NumRB', 'HBA', 'HBD',
'Num_sp', 'Num_sp2', 'Num_sp3', 'F_sp3', 'NumHetero', 'NumAR',
'MolLogP', 'AromaticSpecies', 'ConjugationLength', 'FlexibilityIndex'
]
X=ml_data[x_numeric_columns]
y_efficiency=ml_data['Efficiency(%)_mean']
#Converttobinarylabelbasedonmedian
y_binary=(y_efficiency>y_efficiency.median()).astype(int)
#Featurescaling
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
#Definemodels(adjustedhyperparametersforsmallsamplesize)
models={
'RandomForest':RandomForestClassifier(n_estimators=50,max_depth=3,
random_state=42,min_samples_split=2),
'GradientBoosting':GradientBoostingClassifier(n_estimators=50,max_depth=2,
learning_rate=0.1,random_state=42),
'XGBoost':xgb.XGBClassifier(n_estimators=50,max_depth=2,
learning_rate=0.1,random_state=42,
eval_metric='logloss',verbosity=0),
'LogisticRegression':LogisticRegression(random_state=42,max_iter=1000,C=1.0)
}
#5-Foldcross-validationtoevaluatemodels(suitableforsmalldatasets)
cv_results={}
formodel_name,modelinmodels.items():
#UsescaleddataforLogisticRegression,rawdataforothers
X_for_cv=X_scaledifmodel_name=='LogisticRegression'elseX
#Compute5-FoldCVAUC
cv_scores=cross_val_score(model,X_for_cv,y_binary,cv=5,scoring='roc_auc')
cv_results[model_name]=cv_scores
#Plot2×2ROCcurves
fig,axes=plt.subplots(2,2,figsize=(14,12))
axes=axes.flatten()
roc_results={}
mean_fpr=np.linspace(0,1,100)
foridx,(model_name,model)inenumerate(models.items()):
ax=axes[idx]
X_for_roc=X_scaledifmodel_name=='LogisticRegression'elseX.values
skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
tprs=[]
aucs=[]
fortrain_idx,test_idxinskf.split(X_for_roc,y_binary.values):
X_train,X_test=X_for_roc[train_idx],X_for_roc[test_idx]
y_train,y_test=y_binary.values[train_idx],y_binary.values[test_idx]
model.fit(X_train,y_train)
y_pred_proba=model.predict_proba(X_test)[:,1]
fpr,tpr,_=roc_curve(y_test,y_pred_proba)
auc_score=auc(fpr,tpr)
aucs.append(auc_score)
#InterpolateTPRforaveraging
interp_tpr=np.interp(mean_fpr,fpr,tpr)
interp_tpr[0]=0.0
tprs.append(interp_tpr)
#ComputemeanROC
mean_tpr=np.mean(tprs,axis=0)
mean_tpr[-1]=1.0
mean_auc=np.mean(aucs)
std_auc=np.std(aucs)
#PlotmeanROCcurve
ax.plot(mean_fpr,mean_tpr,color='#1f77b4',lw=2.5,
label=f'MeanROC(AUC={mean_auc:.4f}±{std_auc:.4f})')
#PlotindividualfoldROCcurves
fortprintprs:
ax.plot(mean_fpr,tpr,color='#1f77b4',alpha=0.1,lw=1)
#Randomclassifierbaseline
ax.plot([0,1],[0,1], 'k--',lw=2,label='RandomClassifier(AUC=0.5000)')
ax.set_xlim([0.0,1.0])
ax.set_ylim([0.0,1.05])
ax.set_xlabel('FalsePositiveRate',fontsize=11)
ax.set_ylabel('TruePositiveRate',fontsize=11)
ax.set_title(f'{model_name}',fontsize=12,fontweight='bold')
ax.legend(loc="lowerright",fontsize=10)
ax.grid(True,alpha=0.3)
roc_results[model_name]={'mean_auc':mean_auc, 'std_auc':std_auc, 'fold_aucs':aucs}
plt.suptitle('ROCCurves(5-FoldCross-Validation)-Target:Efficiency%_mean',
fontsize=16,fontweight='bold',y=1.00)
plt.tight_layout()
plt.savefig('ROC_curves_cv_2x2.png',dpi=300,bbox_inches='tight')
plt.show()